---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stress
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: progrium/stress
        env:
        - name: CPU
          value: "4"
        args:
          - --cpu
          - "$(CPU)"
      nodeSelector:
        beta.kubernetes.io/os: linux

